music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^TDT4140_a/$', views.TDT4140_a),
    url(r'^TDT4110_a/$', views.TDT4110_a),
    url(r'^TDT4145_a/$', views.TDT4145_a),
    url(r'^TDT4180_a/$', views.TDT4180_a),
    url(r'^TTM4100_a/$', views.TTM4100_a),

    url(r'^TDT4140_q/$', views.TDT4140_q),
    url(r'^TDT4110_q/$', views.TDT4110_q),
    url(r'^TDT4145_q/$', views.TDT4145_q),
    url(r'^TDT4180_q/$', views.TDT4180_q),
    url(r'^TTM4100_q/$', views.TTM4100_q),

    url(r'^questions/$', views.question, name = 'questions')

]

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django import forms


class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

# superklasse for sporsmål og svar,
# rent funksjonelt er det fa forskjeller pa dem hvis de kommer
# fra samme superklasse.


class Post(models.Model):
    parent_post = models.ForeignKey('self')
    title = forms.CharField(max_length=200)
    posted_by = models.ForeignKey(User)


class Question(Post):
    question_title = Post.title
    content = forms.CharField(
        required=True,
        widget=forms.Textarea,
        max_length=10000,
    )
    rating = forms.IntegerField(
        initial=0,
    )
    is_sticky = forms.BooleanField(initial=False)

    def __str__(self):
        return self.question_title


class Comment(Question):
    reply_to = models.ForeignKey(
        Question,
        on_delete='username="deleted user"',
        )
    body = forms.CharField(
        text=forms.Textarea,
        max_length=10000,
        requir=True,
    )
    rating = forms.IntegerField()


class VotedOn(Post):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE())

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Ask{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:songs' 'all' %}">Pekka 2.0</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Answer</a></li>
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Ask</a></li>
            </ul>
           <!-- <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>-->
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:create_album' %}">
                        <span class="glyphicon glyphicon-i" aria-hidden="true"></span>&nbsp; About
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/create_album.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">


        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Pekka 2.0?</h3>
                    <p><i>Pekka 2.0</i> is a website dedicated to students with questions, and a homage to a certain
                        professor. Here, students, lecturers and others may ask and find answers to various questions
                        related to studies and academic fields.
                    <br>
                    <br>
                        <b>The purpose of <i>Pekka 2.0</i></b> is to rapidly provide answers to whatever questions one might have.
                    As users use Pekka 2.0 more and more, it will be able to find similar questions, and return
                    the most qualified answers readily available by sorting the answers by their credibility
                    and quality.</p>
                    <h3>Tips for questions</h3>
                    <ul>
                        <li>Try to be specific.</li>
                        <li>Put the details in the text, not the title.</li>
                    </ul>
                    <h3>Tips for answering</h3>
                    <ul>
                        <li>Try to visualize or make intuitive explanations.</li>
                        <li>Useful links and images are recommended.</li>
                        <li>Summaries are great.</li>
                    </ul>
                    <h3>Overall participation</h3>
                    <ul>
                        <li>Give credit to good questions and answers. </li>
                        <li>Refrain from off-topic discussions.</li>
                        <li>Be civil.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/create_song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}


music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Her har vi Fag Kode oversikt for "spørr" siden -->
     <div class="row">
            <div class="col-sm-12">
                <h3>Find your subject and ask away!</h3>
                <h2><a href="questions">Ask new questions here</a></h2>
            </div>

            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>

                                <tr>
                                    <th>Fag Kode</th>
                                    <th>Fag Navn</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                    <a href="TDT4140_q">TDT4140</a>
                                    </td>
                                    <td>
                                    PU
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="TDT4145_q">TDT4145</a>
                                    </td>
                                    <td>
                                    Databaser og datamoddelering
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="TDT4180_q">TDT4180</a>
                                    </td>
                                    <td>
                                    Menneske-maskin interaksjon
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="TTM4100_q">TTM4100</a>
                                    </td>
                                    <td>
                                    Kommunikasjon, tjenester og nett
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="TDT4110_q">TDT4110</a>
                                    </td>
                                    <td>
                                    ITGK
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Fag Kode</th>
                                    <th>Fag Navn</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>TDT4140</td>
                                    <td>PU</td>
                                    <td>Ja/Nei</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/login.html
{% extends 'music/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


music/templates/music/register.html
{% extends 'music/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'music:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}Answer{% endblock %}
{% block songs_active %}active{% endblock %}
<!-- Dette er ANSWER!!!! -->
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
    <div class="col-sm-12">
                <h3>Find your subject's code and answer questions to help your classmates out!</h3>
            </div>
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <!--<li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li> -->
                </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <!-- Rekkefølge: Song title, artist, audio file, album, favorite -->
                                <th>Fagkode</th>
                                <th>Fagnavn</th>
                            </tr>
                        </thead>
                        <tbody>
                                <tr>
                                    <td>
                                    <a href="../../TDT4140_a">TDT4140</a>
                                    </td>
                                    <td>
                                    PU
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="../../TDT4145_a">TDT4145</a>
                                    </td>
                                    <td>
                                    Databaser og datamoddelering
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="../../TDT4180_a">TDT4180</a>
                                    </td>
                                    <td>
                                    Menneske-maskin interaksjon
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="../../TTM4100_a">TTM4100</a>
                                    </td>
                                    <td>
                                    Kommunikasjon, tjenester og nett
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    <a href="../../TDT4110_a">TDT4110</a>
                                    </td>
                                    <td>
                                    ITGK
                                    </td>
                                </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}